import { rewardPermissions } from '../reward/reward.policy';
export const ADMIN_PERMISSION_DEFINITIONS = [
  ...['settlements.view','settlements.hold','settlements.adjust','payouts.view','payouts.approve','payouts.process','payouts.confirm','payout_accounts.view','payout_accounts.verify'].map(code=>({code,name:code,description:code,module:'settlements'})),
  ...rewardPermissions.map(code=>({code,name:code,description:code,module:code.split('.')[0]})),
  ...['settings.view','settings.update','settings.countries.manage','settings.currencies.manage','settings.languages.manage','settings.payment_methods.manage','settings.settlement.manage','settings.payout.manage'].map(code=>({code,name:code,description:code,module:'settings'})),
  { code: 'audit_logs.view', name: 'View audit logs', description: 'Read central audit history', module: 'audit_logs' },
  { code: 'audit_logs.export', name: 'Export audit logs', description: 'Export central audit history', module: 'audit_logs' },
  { code: 'refunds.view', name: 'refunds.view', description: 'refunds.view', module: 'refunds' },
  { code: 'refunds.create', name: 'refunds.create', description: 'refunds.create', module: 'refunds' },
  { code: 'refunds.approve', name: 'refunds.approve', description: 'refunds.approve', module: 'refunds' },
  { code: 'refunds.process', name: 'refunds.process', description: 'refunds.process', module: 'refunds' },
  { code: 'refunds.confirm', name: 'refunds.confirm', description: 'refunds.confirm', module: 'refunds' },
  { code: 'returns.view', name: 'returns.view', description: 'returns.view', module: 'returns' },
  { code: 'returns.manage', name: 'returns.manage', description: 'returns.manage', module: 'returns' },

  {
    code: 'users.view',
    name: 'View Users',
    description: 'Allows the Admin to view marketplace users.',
    module: 'users',
  },
  {
    code: 'users.update',
    name: 'Update Users',
    description: 'Allows the Admin to update marketplace user records.',
    module: 'users',
  },
  {
    code: 'users.disable',
    name: 'Disable Users',
    description: 'Allows the Admin to disable marketplace user accounts.',
    module: 'users',
  },
  {
    code: 'users.activate',
    name: 'Activate Users',
    description: 'Allows the Admin to reactivate eligible marketplace users.',
    module: 'users',
  },
  {
    code: 'sellers.view',
    name: 'View Sellers',
    description: 'Allows the Admin to view seller verification records.',
    module: 'sellers',
  },
  {
    code: 'sellers.verify',
    name: 'Verify Sellers',
    description: 'Allows the Admin to approve seller verification requests.',
    module: 'sellers',
  },
  {
    code: 'sellers.reject',
    name: 'Reject Sellers',
    description: 'Allows the Admin to reject seller verification requests.',
    module: 'sellers',
  },
  {
    code: 'products.view',
    name: 'View Products',
    description: 'Allows the Admin to view marketplace products.',
    module: 'products',
  },
  {
    code: 'products.update',
    name: 'Update Products',
    description: 'Allows the Admin to update marketplace products.',
    module: 'products',
  },
  {
    code: 'products.activate',
    name: 'Activate Products',
    description: 'Allows the Admin to activate marketplace products.',
    module: 'products',
  },
  {
    code: 'products.deactivate',
    name: 'Deactivate Products',
    description: 'Allows the Admin to deactivate marketplace products.',
    module: 'products',
  },
  {
    code: 'products.archive',
    name: 'Archive Products',
    description: 'Allows the Admin to archive marketplace products.',
    module: 'products',
  },
  {
    code: 'categories.view',
    name: 'View Categories',
    description: 'Allows the Admin to view all marketplace categories.',
    module: 'categories',
  },
  {
    code: 'categories.create',
    name: 'Create Categories',
    description: 'Allows the Admin to create marketplace categories.',
    module: 'categories',
  },
  {
    code: 'categories.update',
    name: 'Update Categories',
    description: 'Allows the Admin to update marketplace categories.',
    module: 'categories',
  },
  {
    code: 'categories.activate',
    name: 'Activate Categories',
    description: 'Allows the Admin to activate marketplace categories.',
    module: 'categories',
  },
  {
    code: 'categories.deactivate',
    name: 'Deactivate Categories',
    description: 'Allows the Admin to deactivate marketplace categories.',
    module: 'categories',
  },
  {
    code: 'categories.archive',
    name: 'Archive Categories',
    description: 'Allows the Admin to archive marketplace categories.',
    module: 'categories',
  },
  {
    code: 'orders.view',
    name: 'View Orders',
    description: 'Allows the Admin to view marketplace orders.',
    module: 'orders',
  },
  {
    code: 'orders.manage',
    name: 'Manage Orders',
    description: 'Allows the Admin to manage marketplace orders.',
    module: 'orders',
  },
  {
    code: 'orders.cancel',
    name: 'Cancel Orders',
    description: 'Allows the Admin to cancel marketplace orders.',
    module: 'orders',
  },
  {
    code: 'payments.view',
    name: 'View Payments',
    description: 'Allows the Admin to view marketplace payments.',
    module: 'payments',
  },
  {
    code: 'payments.verify',
    name: 'Verify Payments',
    description: 'Allows the Admin to verify manual payments.',
    module: 'payments',
  },
  {
    code: 'payments.reject',
    name: 'Reject Payments',
    description: 'Allows the Admin to reject manual payments.',
    module: 'payments',
  },
  {
    code: 'logistics.view',
    name: 'View Logistics',
    description: 'Allows the Admin to view logistics providers and shipments.',
    module: 'logistics',
  },
  {
    code: 'logistics.manage',
    name: 'Manage Logistics',
    description: 'Allows the Admin to update logistics provider configuration.',
    module: 'logistics',
  },
  {
    code: 'rfqs.view',
    name: 'View RFQs',
    description: 'Allows the Admin to view marketplace RFQs.',
    module: 'rfqs',
  },
  {
    code: 'rfqs.manage',
    name: 'Manage RFQs',
    description: 'Allows the Admin to manage marketplace RFQs.',
    module: 'rfqs',
  },
  {
    code: 'reviews.view',
    name: 'View Reviews',
    description: 'Allows the Admin to view marketplace reviews.',
    module: 'reviews',
  },
  {
    code: 'messages.view',
    name: 'View Message Conversations',
    description: 'Allows the Admin to view Message Center conversations.',
    module: 'messages',
  },
  {
    code: 'messages.view_reports',
    name: 'View Message Reports',
    description: 'Allows the Admin to view reported Message Center content.',
    module: 'messages',
  },
  {
    code: 'messages.moderate',
    name: 'Moderate Messages',
    description: 'Allows the Admin to review reports and moderate Message Center content.',
    module: 'messages',
  },
  {
    code: 'messages.block_conversation',
    name: 'Block Message Conversations',
    description: 'Allows the Admin to block or unblock Message Center conversations.',
    module: 'messages',
  },
  {
    code: 'messages.manage_settings',
    name: 'Manage Message Settings',
    description: 'Allows the Admin to update Message Center limits and attachment rules.',
    module: 'messages',
  },
  {
    code: 'notifications.view',
    name: 'View Notifications',
    description: 'Allows the Admin to view notification history and announcements.',
    module: 'notifications',
  },
  {
    code: 'notifications.manage_announcements',
    name: 'Manage Notification Announcements',
    description: 'Allows the Admin to create and cancel system announcements.',
    module: 'notifications',
  },
  {
    code: 'notifications.view_stats',
    name: 'View Notification Statistics',
    description: 'Allows the Admin to view notification delivery and read statistics.',
    module: 'notifications',
  },
  {
    code: 'notifications.manage_settings',
    name: 'Manage Notification Settings',
    description: 'Allows the Admin to manage notification defaults and retention settings.',
    module: 'notifications',
  },
  {
    code: 'languages.view',
    name: 'View Languages',
    description: 'Allows the Admin to view platform language configuration.',
    module: 'languages',
  },
  {
    code: 'languages.manage',
    name: 'Manage Languages',
    description: 'Allows the Admin to create, update, activate and set default languages.',
    module: 'languages',
  },
  {
    code: 'translations.view',
    name: 'View Translations',
    description: 'Allows the Admin to monitor translation status across marketplace content.',
    module: 'translations',
  },
  {
    code: 'translations.manage',
    name: 'Manage Translations',
    description: 'Allows the Admin to manually override translated marketplace content.',
    module: 'translations',
  },
  {
    code: 'translations.retry',
    name: 'Retry Translations',
    description: 'Allows the Admin to queue failed or stale translations for retry.',
    module: 'translations',
  },
  {
    code: 'search.view_settings',
    name: 'View Search Settings',
    description: 'Allows the Admin to view Search, Discovery and Ranking settings.',
    module: 'search',
  },
  {
    code: 'search.manage_settings',
    name: 'Manage Search Settings',
    description: 'Allows the Admin to update Search, Discovery and Ranking settings.',
    module: 'search',
  },
  {
    code: 'search.view_index',
    name: 'View Search Index',
    description: 'Allows the Admin to view Search index health and update status.',
    module: 'search',
  },
  {
    code: 'search.reindex',
    name: 'Reindex Search',
    description: 'Allows the Admin to request Search reindex operations.',
    module: 'search',
  },
  {
    code: 'reviews.moderate',
    name: 'Moderate Reviews',
    description: 'Allows the Admin to moderate marketplace reviews.',
    module: 'reviews',
  },
  {
    code: 'rewards.manage',
    name: 'Manage Rewards',
    description: 'Allows the Admin to update reward settings and adjust user points.',
    module: 'rewards',
  },
  {
    code: 'subscriptions.view',
    name: 'View Subscriptions',
    description: 'Allows the Admin to view user subscriptions.',
    module: 'subscriptions',
  },
  {
    code: 'subscriptions.manage',
    name: 'Manage Subscriptions',
    description: 'Allows the Admin to manage user subscriptions.',
    module: 'subscriptions',
  },
  {
    code: 'subscription_plans.view',
    name: 'View Subscription Plans',
    description: 'Allows the Admin to view subscription plans.',
    module: 'subscription_plans',
  },
  {
    code: 'subscription_plans.create',
    name: 'Create Subscription Plans',
    description: 'Allows the Admin to create subscription plans.',
    module: 'subscription_plans',
  },
  {
    code: 'subscription_plans.update',
    name: 'Update Subscription Plans',
    description: 'Allows the Admin to update subscription plans.',
    module: 'subscription_plans',
  },
  {
    code: 'subscription_plans.activate',
    name: 'Activate Subscription Plans',
    description: 'Allows the Admin to activate subscription plans.',
    module: 'subscription_plans',
  },
  {
    code: 'subscription_plans.deactivate',
    name: 'Deactivate Subscription Plans',
    description: 'Allows the Admin to deactivate subscription plans.',
    module: 'subscription_plans',
  },
  {
    code: 'analytics.view_overview',
    name: 'View Analytics Overview',
    description: 'Allows the Admin to view marketplace analytics overview.',
    module: 'analytics',
  },
  {
    code: 'analytics.view_users',
    name: 'View User Analytics',
    description: 'Allows the Admin to view user analytics.',
    module: 'analytics',
  },
  {
    code: 'analytics.view_sellers',
    name: 'View Seller Analytics',
    description: 'Allows the Admin to view seller analytics.',
    module: 'analytics',
  },
  {
    code: 'analytics.view_buyers',
    name: 'View Buyer Analytics',
    description: 'Allows the Admin to view buyer analytics.',
    module: 'analytics',
  },
  {
    code: 'analytics.view_products',
    name: 'View Product Analytics',
    description: 'Allows the Admin to view product analytics.',
    module: 'analytics',
  },
  {
    code: 'analytics.view_orders',
    name: 'View Order Analytics',
    description: 'Allows the Admin to view order analytics.',
    module: 'analytics',
  },
  {
    code: 'analytics.view_payments',
    name: 'View Payment Analytics',
    description: 'Allows the Admin to view payment analytics.',
    module: 'analytics',
  },
  {
    code: 'analytics.view_rfqs',
    name: 'View RFQ Analytics',
    description: 'Allows the Admin to view RFQ analytics.',
    module: 'analytics',
  },
  {
    code: 'analytics.view_revenue',
    name: 'View Revenue Analytics',
    description: 'Allows the Admin to view revenue analytics.',
    module: 'analytics',
  },
  {
    code: 'analytics.view_subscriptions',
    name: 'View Subscription Analytics',
    description: 'Allows the Admin to view subscription analytics.',
    module: 'analytics',
  },
  {
    code: 'analytics.view_logistics',
    name: 'View Logistics Analytics',
    description: 'Allows the Admin to view logistics analytics.',
    module: 'analytics',
  },
  {
    code: 'analytics.export_reports',
    name: 'Export Reports',
    description: 'Allows the Admin to export analytics reports.',
    module: 'analytics',
  },
  {
    code: 'analytics.rebuild',
    name: 'Rebuild Analytics',
    description: 'Allows the Admin to rebuild analytics aggregates.',
    module: 'analytics',
  },
  {
    code: 'disputes.view',
    name: 'View Disputes',
    description: 'Allows the Admin to view marketplace disputes.',
    module: 'disputes',
  },
  {
    code: 'disputes.assign',
    name: 'Assign Disputes',
    description: 'Allows the Admin to assign marketplace disputes.',
    module: 'disputes',
  },
  {
    code: 'disputes.manage',
    name: 'Manage Disputes',
    description: 'Allows the Admin to manage marketplace disputes.',
    module: 'disputes',
  },
  {
    code: 'disputes.request_information',
    name: 'Request Dispute Information',
    description: 'Allows the Admin to request dispute information.',
    module: 'disputes',
  },
  {
    code: 'disputes.resolve',
    name: 'Resolve Disputes',
    description: 'Allows the Admin to resolve marketplace disputes.',
    module: 'disputes',
  },
  {
    code: 'disputes.close',
    name: 'Close Disputes',
    description: 'Allows the Admin to close marketplace disputes.',
    module: 'disputes',
  },
  {
    code: 'admins.view',
    name: 'View Admins',
    description: 'Allows the Admin to view administrative accounts.',
    module: 'admins',
  },
  {
    code: 'admins.create',
    name: 'Create Admins',
    description: 'Allows the Admin to create administrative accounts.',
    module: 'admins',
  },
  {
    code: 'admins.update',
    name: 'Update Admins',
    description: 'Allows the Admin to update administrative accounts.',
    module: 'admins',
  },
  {
    code: 'admins.activate',
    name: 'Activate Admins',
    description: 'Allows the Admin to reactivate administrative accounts.',
    module: 'admins',
  },
  {
    code: 'admins.deactivate',
    name: 'Deactivate Admins',
    description: 'Allows the Admin to deactivate administrative accounts.',
    module: 'admins',
  },
  {
    code: 'roles.view',
    name: 'View Roles',
    description: 'Allows the Admin to view admin roles.',
    module: 'roles',
  },
  {
    code: 'roles.create',
    name: 'Create Roles',
    description: 'Allows the Admin to create admin roles.',
    module: 'roles',
  },
  {
    code: 'roles.update',
    name: 'Update Roles',
    description: 'Allows the Admin to update admin roles.',
    module: 'roles',
  },
  {
    code: 'roles.deactivate',
    name: 'Deactivate Roles',
    description: 'Allows the Admin to deactivate admin roles.',
    module: 'roles',
  },
  {
    code: 'permissions.view',
    name: 'View Permissions',
    description: 'Allows the Admin to view backend-defined permissions.',
    module: 'permissions',
  },
  {
    code: 'permissions.assign',
    name: 'Assign Permissions',
    description: 'Allows the Admin to assign permissions to roles.',
    module: 'permissions',
  },
] as const;

export type AdminPermissionCode =
  (typeof ADMIN_PERMISSION_DEFINITIONS)[number]['code'];

export const ADMIN_PERMISSION_CODES = ADMIN_PERMISSION_DEFINITIONS.map(
  (permission) => permission.code,
);
