import {MigrationInterface,QueryRunner} from 'typeorm';
import seeds from './system-settings-seed.json';
export class AddSystemSettings1787520019000 implements MigrationInterface {
 async up(q:QueryRunner):Promise<void> {
  await q.query(`CREATE TABLE system_settings (id varchar(36) NOT NULL PRIMARY KEY, \`key\` varchar(120) NOT NULL UNIQUE, category varchar(40) NOT NULL, value json NULL, valueType enum('string','number','boolean','array','object') NOT NULL, description text NULL, isPublic boolean NOT NULL DEFAULT false, isEditable boolean NOT NULL DEFAULT true, updatedBy varchar(36) NULL, createdAt timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updatedAt timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), KEY IDX_settings_category(category)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
  for(const s of seeds) await q.query('INSERT INTO system_settings (id,`key`,category,value,valueType,description,isPublic,isEditable) VALUES (UUID(),?,?,?,?,?,?,?)',[s.key,s.category,JSON.stringify(s.value),s.valueType,s.description,s.isPublic,s.isEditable]);
  await q.query("UPDATE system_settings SET value=(SELECT CAST(returnWindowDays AS JSON) FROM after_sales_settings LIMIT 1) WHERE `key`='returnWindowDays' AND EXISTS(SELECT 1 FROM after_sales_settings)");
  await q.query("UPDATE system_settings SET value=(SELECT JSON_QUOTE(code) FROM languages WHERE isDefault=true AND status='active' LIMIT 1) WHERE `key`='defaultLanguage' AND EXISTS(SELECT 1 FROM languages WHERE isDefault=true AND status='active')");
  await q.query(`CREATE TABLE countries (id varchar(36) NOT NULL PRIMARY KEY, code varchar(2) NOT NULL UNIQUE, name varchar(120) NOT NULL, phoneCode varchar(8) NULL, status enum('active','inactive') NOT NULL DEFAULT 'active', createdAt timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updatedAt timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
  await q.query(`CREATE TABLE currencies (id varchar(36) NOT NULL PRIMARY KEY, code varchar(3) NOT NULL UNIQUE, name varchar(120) NOT NULL, symbol varchar(8) NULL, decimalPlaces int NOT NULL DEFAULT 2, status enum('active','inactive') NOT NULL DEFAULT 'active', createdAt timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updatedAt timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
  for(const values of [['NG','Nigeria','+234'],['GH','Ghana','+233'],['KE','Kenya','+254']])await q.query('INSERT INTO countries(id,code,name,phoneCode) VALUES(UUID(),?,?,?)',values);
  for(const values of [['NGN','Nigerian Naira','₦'],['GHS','Ghanaian Cedi','GH₵'],['USD','US Dollar','$'],['KES','Kenyan Shilling','KSh'],['EUR','Euro','€'],['GBP','Pound Sterling','£'],['ZAR','South African Rand','R'],['XOF','West African CFA Franc','CFA'],['XAF','Central African CFA Franc','FCFA']])await q.query('INSERT INTO currencies(id,code,name,symbol) VALUES(UUID(),?,?,?)',values);
  await q.query(`CREATE TABLE payment_method_configs (id varchar(36) NOT NULL PRIMARY KEY, code varchar(80) NOT NULL UNIQUE, displayName varchar(120) NOT NULL, status enum('active','inactive') NOT NULL DEFAULT 'active', supportedCurrencies json NOT NULL, paymentContext json NULL, sortOrder int NOT NULL DEFAULT 0, createdAt timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updatedAt timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
  await q.query('INSERT INTO payment_method_configs (id,code,displayName,status,supportedCurrencies,paymentContext,sortOrder) SELECT UUID(),code,name,status,supportedCurrencies,supportedSourceTypes,sortOrder FROM payment_providers');
  for(const code of ['settings.view','settings.update','settings.countries.manage','settings.currencies.manage','settings.languages.manage','settings.payment_methods.manage','settings.settlement.manage','settings.payout.manage'])await q.query('INSERT IGNORE INTO permissions(id,code,name,description,module) VALUES(UUID(),?,?,?,?)',[code,code,code,'settings']);
  await q.query("INSERT IGNORE INTO admin_role_permissions(id,roleId,permissionId) SELECT UUID(),rp.roleId,newp.id FROM admin_role_permissions rp JOIN permissions oldp ON oldp.id=rp.permissionId JOIN permissions newp ON newp.code='settings.languages.manage' WHERE oldp.code='languages.manage'");
 }
 async down():Promise<void>{throw new Error('Configuration and audit history must be retained; use a reviewed forward migration.');}
}
