import { MigrationInterface, QueryRunner } from 'typeorm';
export class AddAfterSales1787520017000 implements MigrationInterface {
 async up(q: QueryRunner): Promise<void> {
  await q.query("CREATE TABLE `returns` (\n`id` varchar(36) NOT NULL PRIMARY KEY,\n`returnNumber` varchar(40) NOT NULL,\n`refundRequired` boolean NOT NULL DEFAULT true,\n`orderId` varchar(36) NOT NULL,\n`buyerId` varchar(36) NOT NULL,\n`sellerId` varchar(36) NOT NULL,\n`reason` varchar(160) NOT NULL,\n`description` text NOT NULL,\n`status` varchar(30) NOT NULL DEFAULT 'requested',\n`returnMethod` varchar(160) NULL,\n`returnProviderName` varchar(160) NULL,\n`returnTrackingId` varchar(160) NULL,\n`deliveryContact` varchar(160) NULL,\n`returnTrackingUrl` varchar(1000) NULL,\n`shipmentNotes` text NULL,\n`responseNotes` text NULL,\n`approvedBy` varchar(36) NULL,\n`refundId` varchar(36) NULL,\n`approvedAt` timestamp NULL,\n`receivedAt` timestamp NULL,\n`policySnapshot` json NOT NULL,\n`createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n`updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\nUNIQUE KEY `IDX_returns_0` (`returnNumber`),\nKEY `IDX_returns_1` (`orderId`, `status`),\nKEY `IDX_returns_2` (`buyerId`, `status`),\nKEY `IDX_returns_3` (`sellerId`, `status`),\nCONSTRAINT `FK_returns_orderId` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`) ON DELETE RESTRICT,\nCONSTRAINT `FK_returns_buyerId` FOREIGN KEY (`buyerId`) REFERENCES `users` (`id`) ON DELETE RESTRICT,\nCONSTRAINT `FK_returns_sellerId` FOREIGN KEY (`sellerId`) REFERENCES `users` (`id`) ON DELETE RESTRICT\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("CREATE TABLE `return_items` (\n`id` varchar(36) NOT NULL PRIMARY KEY,\n`returnId` varchar(36) NOT NULL,\n`orderItemId` varchar(36) NOT NULL,\n`quantity` decimal(18,3) NOT NULL,\n`reason` varchar(160) NULL,\n`createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n`updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\nUNIQUE KEY `IDX_return_items_0` (`returnId`, `orderItemId`),\nKEY `IDX_return_items_1` (`orderItemId`),\nCONSTRAINT `FK_return_items_returnId` FOREIGN KEY (`returnId`) REFERENCES `returns` (`id`) ON DELETE RESTRICT,\nCONSTRAINT `FK_return_items_orderItemId` FOREIGN KEY (`orderItemId`) REFERENCES `order_items` (`id`) ON DELETE RESTRICT\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("CREATE TABLE `return_evidence` (\n`id` varchar(36) NOT NULL PRIMARY KEY,\n`userId` varchar(36) NOT NULL,\n`returnId` varchar(36) NULL,\n`fileName` varchar(255) NOT NULL,\n`fileUrl` varchar(1000) NOT NULL,\n`storedName` varchar(500) NOT NULL,\n`mimeType` varchar(120) NOT NULL,\n`sizeBytes` int NOT NULL,\n`expiresAt` timestamp NOT NULL,\n`createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n`updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\nKEY `IDX_return_evidence_0` (`returnId`),\nCONSTRAINT `FK_return_evidence_returnId` FOREIGN KEY (`returnId`) REFERENCES `returns` (`id`) ON DELETE RESTRICT,\nCONSTRAINT `FK_return_evidence_userId` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE RESTRICT\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("CREATE TABLE `refunds` (\n`id` varchar(36) NOT NULL PRIMARY KEY,\n`refundNumber` varchar(40) NOT NULL,\n`paymentId` varchar(36) NOT NULL,\n`orderId` varchar(36) NOT NULL,\n`buyerId` varchar(36) NOT NULL,\n`sellerId` varchar(36) NOT NULL,\n`requestedBy` varchar(36) NOT NULL,\n`cancellationId` varchar(36) NULL,\n`returnId` varchar(36) NULL,\n`disputeId` varchar(36) NULL,\n`approvedBy` varchar(36) NULL,\n`sourceType` varchar(30) NOT NULL,\n`refundType` varchar(30) NOT NULL,\n`amount` decimal(18,2) NOT NULL,\n`currency` varchar(3) NOT NULL,\n`status` varchar(30) NOT NULL DEFAULT 'pending',\n`reason` text NOT NULL,\n`gateway` varchar(80) NOT NULL,\n`gatewayRefundReference` varchar(160) NULL,\n`processedAt` timestamp NULL,\n`completedAt` timestamp NULL,\n`failedAt` timestamp NULL,\n`failureReason` text NULL,\n`breakdown` json NOT NULL,\n`financialSnapshot` json NOT NULL,\n`processingMode` varchar(20) NULL,\n`attemptCount` int NOT NULL DEFAULT 0,\n`createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n`updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\nUNIQUE KEY `IDX_refunds_0` (`refundNumber`),\nUNIQUE KEY `IDX_refunds_1` (`cancellationId`),\nUNIQUE KEY `IDX_refunds_2` (`returnId`),\nUNIQUE KEY `IDX_refunds_3` (`disputeId`),\nKEY `IDX_refunds_4` (`orderId`, `status`),\nKEY `IDX_refunds_5` (`paymentId`, `status`),\nUNIQUE KEY `IDX_refunds_6` (`gateway`, `gatewayRefundReference`),\nCONSTRAINT `FK_refunds_orderId` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`) ON DELETE RESTRICT,\nCONSTRAINT `FK_refunds_paymentId` FOREIGN KEY (`paymentId`) REFERENCES `payments` (`id`) ON DELETE RESTRICT,\nCONSTRAINT `FK_refunds_cancellationId` FOREIGN KEY (`cancellationId`) REFERENCES `order_cancellation_requests` (`id`) ON DELETE RESTRICT,\nCONSTRAINT `FK_refunds_returnId` FOREIGN KEY (`returnId`) REFERENCES `returns` (`id`) ON DELETE RESTRICT,\nCONSTRAINT `FK_refunds_disputeId` FOREIGN KEY (`disputeId`) REFERENCES `disputes` (`id`) ON DELETE RESTRICT\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("CREATE TABLE `financial_adjustments` (\n`id` varchar(36) NOT NULL PRIMARY KEY,\n`orderId` varchar(36) NOT NULL,\n`paymentId` varchar(36) NOT NULL,\n`refundId` varchar(36) NOT NULL,\n`adjustmentType` varchar(40) NOT NULL,\n`amount` decimal(18,2) NOT NULL,\n`currency` varchar(3) NOT NULL,\n`direction` varchar(10) NOT NULL,\n`reason` text NOT NULL,\n`createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n`updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\nUNIQUE KEY `IDX_financial_adjustments_0` (`refundId`, `adjustmentType`),\nCONSTRAINT `FK_financial_adjustments_orderId` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`) ON DELETE RESTRICT,\nCONSTRAINT `FK_financial_adjustments_paymentId` FOREIGN KEY (`paymentId`) REFERENCES `payments` (`id`) ON DELETE RESTRICT,\nCONSTRAINT `FK_financial_adjustments_refundId` FOREIGN KEY (`refundId`) REFERENCES `refunds` (`id`) ON DELETE RESTRICT\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("CREATE TABLE `after_sales_settings` (\n`id` varchar(36) NOT NULL PRIMARY KEY,\n`returnWindowDays` int NOT NULL DEFAULT 7,\n`allowChangedMind` boolean NOT NULL DEFAULT 0,\n`refundLogisticsOnCancellation` boolean NOT NULL DEFAULT 0,\n`reverseTransactionFee` boolean NOT NULL DEFAULT 1,\n`nonReturnableProductIds` json NOT NULL,\n`createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n`updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("CREATE TABLE `after_sales_events` (\n`id` varchar(36) NOT NULL PRIMARY KEY,\n`orderId` varchar(36) NOT NULL,\n`entityId` varchar(36) NOT NULL,\n`actorId` varchar(36) NOT NULL,\n`actorType` varchar(20) NOT NULL,\n`eventType` varchar(120) NOT NULL,\n`payload` json NOT NULL,\n`deliveredAt` timestamp NULL,\n`createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n`updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\nKEY `IDX_after_sales_events_0` (`deliveredAt`, `createdAt`),\nKEY `IDX_after_sales_events_1` (`entityId`),\nCONSTRAINT `FK_after_sales_events_orderId` FOREIGN KEY (`orderId`) REFERENCES `orders` (`id`) ON DELETE RESTRICT\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("ALTER TABLE disputes ADD returnId varchar(36) NULL, ADD CONSTRAINT FK_disputes_returnId FOREIGN KEY (returnId) REFERENCES returns(id) ON DELETE RESTRICT");
  await q.query("ALTER TABLE order_cancellation_requests MODIFY status ENUM('pending','approved','rejected','completed') NOT NULL DEFAULT 'pending', ADD cancellationNumber varchar(40) NULL, ADD refundRequired boolean NOT NULL DEFAULT false, ADD refundId varchar(36) NULL, ADD cancelledAt timestamp NULL");
  await q.query("UPDATE order_cancellation_requests SET cancellationNumber = CONCAT('CAN-', id)");
  await q.query("ALTER TABLE order_cancellation_requests MODIFY cancellationNumber varchar(40) NOT NULL, ADD UNIQUE KEY UQ_cancellation_number (cancellationNumber)");
  await q.query("INSERT INTO after_sales_settings (id, nonReturnableProductIds) VALUES ('00000000-0000-4000-8000-000000000020', JSON_ARRAY())");
  await q.query("INSERT IGNORE INTO permissions (id, code, name, description, module) VALUES (UUID(), ?, ?, ?, ?)", ["refunds.view", "refunds.view", "refunds.view", "refunds"]);
  await q.query("INSERT IGNORE INTO permissions (id, code, name, description, module) VALUES (UUID(), ?, ?, ?, ?)", ["refunds.create", "refunds.create", "refunds.create", "refunds"]);
  await q.query("INSERT IGNORE INTO permissions (id, code, name, description, module) VALUES (UUID(), ?, ?, ?, ?)", ["refunds.approve", "refunds.approve", "refunds.approve", "refunds"]);
  await q.query("INSERT IGNORE INTO permissions (id, code, name, description, module) VALUES (UUID(), ?, ?, ?, ?)", ["refunds.process", "refunds.process", "refunds.process", "refunds"]);
  await q.query("INSERT IGNORE INTO permissions (id, code, name, description, module) VALUES (UUID(), ?, ?, ?, ?)", ["refunds.confirm", "refunds.confirm", "refunds.confirm", "refunds"]);
  await q.query("INSERT IGNORE INTO permissions (id, code, name, description, module) VALUES (UUID(), ?, ?, ?, ?)", ["returns.view", "returns.view", "returns.view", "returns"]);
  await q.query("INSERT IGNORE INTO permissions (id, code, name, description, module) VALUES (UUID(), ?, ?, ?, ?)", ["returns.manage", "returns.manage", "returns.manage", "returns"]);
 }
 async down(): Promise<void> { throw new Error('Financial history must be retained. Use a reviewed forward migration to roll back after-sales changes.'); }
}
