import { MigrationInterface, QueryRunner } from 'typeorm';
export class AddSellerSettlements1787520022000 implements MigrationInterface {
 name='AddSellerSettlements1787520022000';
 async up(q:QueryRunner):Promise<void>{
  await q.query("CREATE TABLE seller_payout_accounts (id VARCHAR(36) NOT NULL PRIMARY KEY, `sellerId` VARCHAR(36) NOT NULL, `accountType` VARCHAR(30) NOT NULL, `accountName` VARCHAR(160) NOT NULL, `accountNumberEncrypted` TEXT NOT NULL, `maskedAccountNumber` VARCHAR(40) NOT NULL, `bankCode` VARCHAR(40) NULL, `bankName` VARCHAR(160) NOT NULL, `country` VARCHAR(2) NOT NULL, `currency` VARCHAR(3) NOT NULL, `providerRecipientId` VARCHAR(100) NULL, `isDefault` BOOLEAN NOT NULL DEFAULT false, `status` VARCHAR(20) NOT NULL DEFAULT 'pending', `version` INT NOT NULL DEFAULT 1, `verifiedAt` TIMESTAMP(6) NULL, `verifiedBy` VARCHAR(36) NULL, createdAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updatedAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("CREATE TABLE seller_settlements (id VARCHAR(36) NOT NULL PRIMARY KEY, `settlementNumber` VARCHAR(50) NOT NULL UNIQUE, `sellerId` VARCHAR(36) NOT NULL, `orderId` VARCHAR(36) NOT NULL, `sellerOrderId` VARCHAR(36) NOT NULL UNIQUE, `paymentId` VARCHAR(36) NOT NULL, `status` VARCHAR(20) NOT NULL DEFAULT 'pending', `grossProductAmount` DECIMAL(18,2) NOT NULL, `logisticsAmount` DECIMAL(18,2) NOT NULL, `transactionFeePercentage` DECIMAL(18,2) NOT NULL, `transactionFeeAmount` DECIMAL(18,2) NOT NULL, `refundAmount` DECIMAL(18,2) NOT NULL DEFAULT '0.00', `adjustmentAmount` DECIMAL(18,2) NOT NULL DEFAULT '0.00', `netSettlementAmount` DECIMAL(18,2) NOT NULL, `settlementCurrency` VARCHAR(3) NOT NULL, `holdDays` INT NOT NULL, `eligibleAt` TIMESTAMP(6) NULL, `payoutId` VARCHAR(36) NULL, `financialSnapshot` JSON NOT NULL, createdAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updatedAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("CREATE TABLE settlement_holds (id VARCHAR(36) NOT NULL PRIMARY KEY, `settlementId` VARCHAR(36) NOT NULL, `holdCode` VARCHAR(60) NOT NULL, `reason` TEXT NULL, `sourceType` VARCHAR(30) NOT NULL, `sourceId` VARCHAR(36) NULL, `status` VARCHAR(20) NOT NULL DEFAULT 'active', `heldBy` VARCHAR(36) NULL, `heldAt` TIMESTAMP(6) NOT NULL, `releasedBy` VARCHAR(36) NULL, `releasedAt` TIMESTAMP(6) NULL, createdAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updatedAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("CREATE TABLE seller_settlement_adjustments (id VARCHAR(36) NOT NULL PRIMARY KEY, `sellerId` VARCHAR(36) NOT NULL, `settlementId` VARCHAR(36) NULL, `sellerOrderId` VARCHAR(36) NOT NULL, `adjustmentType` VARCHAR(40) NOT NULL, `amount` DECIMAL(18,2) NOT NULL, `currency` VARCHAR(3) NOT NULL, `direction` VARCHAR(10) NOT NULL, `sourceType` VARCHAR(40) NOT NULL, `sourceId` VARCHAR(80) NULL, `reason` TEXT NOT NULL, `status` VARCHAR(20) NOT NULL DEFAULT 'active', `idempotencyKey` VARCHAR(191) NOT NULL UNIQUE, `createdBy` VARCHAR(36) NULL, createdAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("CREATE TABLE seller_payouts (id VARCHAR(36) NOT NULL PRIMARY KEY, `payoutNumber` VARCHAR(50) NOT NULL UNIQUE, `sellerId` VARCHAR(36) NOT NULL, `settlementId` VARCHAR(36) NOT NULL UNIQUE, `payoutAccountId` VARCHAR(36) NOT NULL, `accountVersion` INT NOT NULL, `destinationEncrypted` TEXT NOT NULL, `destination` JSON NOT NULL, `financialSnapshot` JSON NOT NULL, `amount` DECIMAL(18,2) NOT NULL, `currency` VARCHAR(3) NOT NULL, `status` VARCHAR(20) NOT NULL DEFAULT 'pending', `method` VARCHAR(30) NOT NULL, `provider` VARCHAR(40) NULL, `providerReference` VARCHAR(160) NULL UNIQUE, `approvedBy` VARCHAR(36) NULL, `approvedAt` TIMESTAMP(6) NULL, `processingBy` VARCHAR(36) NULL, `processingAt` TIMESTAMP(6) NULL, `completedAt` TIMESTAMP(6) NULL, `failedAt` TIMESTAMP(6) NULL, `failureReason` TEXT NULL, `attemptCount` INT NOT NULL DEFAULT 0, createdAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updatedAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("CREATE TABLE payout_attempts (id VARCHAR(36) NOT NULL PRIMARY KEY, `payoutId` VARCHAR(36) NOT NULL, `attemptNumber` INT NOT NULL, `reference` VARCHAR(100) NOT NULL UNIQUE, `status` VARCHAR(20) NOT NULL, `amount` DECIMAL(18,2) NOT NULL, `currency` VARCHAR(3) NOT NULL, `recipientId` VARCHAR(100) NULL, `destination` JSON NOT NULL, `provider` VARCHAR(40) NOT NULL, `providerReference` VARCHAR(160) NULL, `initiatedBy` VARCHAR(36) NULL, `completedAt` TIMESTAMP(6) NULL, `failureReason` TEXT NULL, createdAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updatedAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("CREATE TABLE settlement_adjustment_allocations (id VARCHAR(36) NOT NULL PRIMARY KEY, `adjustmentId` VARCHAR(36) NOT NULL, `payoutId` VARCHAR(36) NOT NULL, `amount` DECIMAL(18,2) NOT NULL, `status` VARCHAR(20) NOT NULL, createdAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updatedAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("CREATE TABLE settlement_events (id VARCHAR(36) NOT NULL PRIMARY KEY, `sellerId` VARCHAR(36) NOT NULL, `settlementId` VARCHAR(36) NULL, `payoutId` VARCHAR(36) NULL, `eventCode` VARCHAR(100) NOT NULL, `actorId` VARCHAR(36) NULL, `payload` JSON NOT NULL, `deliveredAt` TIMESTAMP(6) NULL, createdAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  await q.query("ALTER TABLE seller_payout_accounts ADD defaultCurrency VARCHAR(3) GENERATED ALWAYS AS (CASE WHEN isDefault THEN currency ELSE NULL END) STORED, ADD UNIQUE KEY UQ_payout_default(sellerId,defaultCurrency)");
  await q.query("ALTER TABLE settlement_holds ADD UNIQUE KEY UQ_settlement_hold(settlementId,holdCode)");
  await q.query("ALTER TABLE payout_attempts ADD UNIQUE KEY UQ_payout_attempt(payoutId,attemptNumber)");
  await q.query("ALTER TABLE settlement_adjustment_allocations ADD UNIQUE KEY UQ_adjustment_allocation(adjustmentId,payoutId)");
  await q.query("ALTER TABLE seller_settlements ADD KEY IDX_settlement_status(status,eligibleAt), ADD KEY IDX_settlement_seller(sellerId,createdAt)");
  await q.query("ALTER TABLE seller_payouts ADD KEY IDX_payout_seller(sellerId,status)");
  await q.query("ALTER TABLE settlement_events ADD KEY IDX_settlement_outbox(deliveredAt,createdAt)");
  await q.query("ALTER TABLE seller_payout_accounts ADD FOREIGN KEY (sellerId) REFERENCES users(id) ON DELETE RESTRICT");
  await q.query("ALTER TABLE seller_settlements ADD FOREIGN KEY (orderId) REFERENCES orders(id) ON DELETE RESTRICT");
  await q.query("ALTER TABLE seller_settlements ADD FOREIGN KEY (sellerId) REFERENCES users(id) ON DELETE RESTRICT");
  await q.query("ALTER TABLE seller_settlements ADD FOREIGN KEY (paymentId) REFERENCES payments(id) ON DELETE RESTRICT");
  await q.query("ALTER TABLE settlement_holds ADD FOREIGN KEY (settlementId) REFERENCES seller_settlements(id) ON DELETE RESTRICT");
  await q.query("ALTER TABLE seller_settlement_adjustments ADD FOREIGN KEY (sellerId) REFERENCES users(id) ON DELETE RESTRICT");
  await q.query("ALTER TABLE seller_settlement_adjustments ADD FOREIGN KEY (settlementId) REFERENCES seller_settlements(id) ON DELETE RESTRICT");
  await q.query("ALTER TABLE seller_settlement_adjustments ADD FOREIGN KEY (sellerOrderId) REFERENCES orders(id) ON DELETE RESTRICT");
  await q.query("ALTER TABLE seller_payouts ADD FOREIGN KEY (settlementId) REFERENCES seller_settlements(id) ON DELETE RESTRICT");
  await q.query("ALTER TABLE seller_payouts ADD FOREIGN KEY (payoutAccountId) REFERENCES seller_payout_accounts(id) ON DELETE RESTRICT");
  await q.query("ALTER TABLE payout_attempts ADD FOREIGN KEY (payoutId) REFERENCES seller_payouts(id) ON DELETE RESTRICT");
  await q.query("ALTER TABLE settlement_adjustment_allocations ADD FOREIGN KEY (adjustmentId) REFERENCES seller_settlement_adjustments(id) ON DELETE RESTRICT");
  await q.query("ALTER TABLE settlement_adjustment_allocations ADD FOREIGN KEY (payoutId) REFERENCES seller_payouts(id) ON DELETE RESTRICT");
  await q.query("ALTER TABLE seller_payouts ADD CHECK (amount >= 0)");
  await q.query("ALTER TABLE payout_attempts ADD CHECK (amount >= 0)");
  await q.query("ALTER TABLE seller_settlement_adjustments ADD CHECK (amount >= 0)");
  await q.query("ALTER TABLE settlement_adjustment_allocations ADD CHECK (amount >= 0)");
  await q.query("CREATE TRIGGER seller_payouts_no_delete BEFORE DELETE ON seller_payouts FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Financial history cannot be deleted'");
  await q.query("CREATE TRIGGER payout_attempts_no_delete BEFORE DELETE ON payout_attempts FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Financial history cannot be deleted'");
  await q.query("CREATE TRIGGER seller_settlement_adjustments_no_delete BEFORE DELETE ON seller_settlement_adjustments FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Financial history cannot be deleted'");
  await q.query("CREATE TRIGGER settlement_adjustment_immutable BEFORE UPDATE ON seller_settlement_adjustments FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Adjustments are append only'");
  await q.query("CREATE TRIGGER seller_payouts_immutable BEFORE UPDATE ON seller_payouts FOR EACH ROW BEGIN IF OLD.status = 'successful' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Successful payout history is immutable'; END IF; END");
  await q.query("CREATE TRIGGER payout_attempts_immutable BEFORE UPDATE ON payout_attempts FOR EACH ROW BEGIN IF OLD.status = 'successful' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Successful payout history is immutable'; END IF; END");
  await q.query("INSERT INTO permissions(id,code,name,description,module,status) VALUES(UUID(),?,?,?,'settlements','active') ON DUPLICATE KEY UPDATE code=VALUES(code)",["settlements.view","settlements.view","settlements view"]);
  await q.query("INSERT INTO permissions(id,code,name,description,module,status) VALUES(UUID(),?,?,?,'settlements','active') ON DUPLICATE KEY UPDATE code=VALUES(code)",["settlements.hold","settlements.hold","settlements hold"]);
  await q.query("INSERT INTO permissions(id,code,name,description,module,status) VALUES(UUID(),?,?,?,'settlements','active') ON DUPLICATE KEY UPDATE code=VALUES(code)",["settlements.adjust","settlements.adjust","settlements adjust"]);
  await q.query("INSERT INTO permissions(id,code,name,description,module,status) VALUES(UUID(),?,?,?,'settlements','active') ON DUPLICATE KEY UPDATE code=VALUES(code)",["payouts.view","payouts.view","payouts view"]);
  await q.query("INSERT INTO permissions(id,code,name,description,module,status) VALUES(UUID(),?,?,?,'settlements','active') ON DUPLICATE KEY UPDATE code=VALUES(code)",["payouts.approve","payouts.approve","payouts approve"]);
  await q.query("INSERT INTO permissions(id,code,name,description,module,status) VALUES(UUID(),?,?,?,'settlements','active') ON DUPLICATE KEY UPDATE code=VALUES(code)",["payouts.process","payouts.process","payouts process"]);
  await q.query("INSERT INTO permissions(id,code,name,description,module,status) VALUES(UUID(),?,?,?,'settlements','active') ON DUPLICATE KEY UPDATE code=VALUES(code)",["payouts.confirm","payouts.confirm","payouts confirm"]);
  await q.query("INSERT INTO permissions(id,code,name,description,module,status) VALUES(UUID(),?,?,?,'settlements','active') ON DUPLICATE KEY UPDATE code=VALUES(code)",["payout_accounts.view","payout_accounts.view","payout_accounts view"]);
  await q.query("INSERT INTO permissions(id,code,name,description,module,status) VALUES(UUID(),?,?,?,'settlements','active') ON DUPLICATE KEY UPDATE code=VALUES(code)",["payout_accounts.verify","payout_accounts.verify","payout_accounts verify"]);
 }
 async down(q:QueryRunner):Promise<void>{
  await q.query("DROP TABLE settlement_events");
  await q.query("DROP TABLE settlement_adjustment_allocations");
  await q.query("DROP TABLE payout_attempts");
  await q.query("DROP TABLE seller_payouts");
  await q.query("DROP TABLE seller_settlement_adjustments");
  await q.query("DROP TABLE settlement_holds");
  await q.query("DROP TABLE seller_settlements");
  await q.query("DROP TABLE seller_payout_accounts");
  await q.query("DELETE rp FROM admin_role_permissions rp JOIN permissions p ON p.id=rp.permissionId WHERE p.module='settlements'");
  await q.query("DELETE FROM permissions WHERE module='settlements'");
 }
}
